---
sidebar_position: 9
---

import Tabs from '@theme/Tabs';                                                                                             
import TabItem from '@theme/TabItem';

# Exception Handling

Exception handling is a mechanism in object-oriented programming that allows a
program to handle runtime errors and unexpected events that can occur during the
execution of a program. Exceptions are objects that represent errors, and they
can be thrown by code that detects an error condition. When an exception is
thrown, it is caught by a handler that can take appropriate actions, such as
**logging an error message, displaying a warning to the user, or attempting to
recover from the error**.

Exceptions are generally handled through a `try`-`catch` block. The code that
may throw an exception is enclosed within a try block, and any exceptions that
are thrown are caught by one or more catch blocks. Each catch block specifies
the type of exception it can handle, and the code within the block is executed
if an exception of that type is thrown.

For example, consider the following Java code that reads a number from the user
and attempts to convert it to an integer:

<Tabs>
  <TabItem value="java" label="Java">

```java
import java.util.InputMismatchException;
import java.util.Scanner;

public class Example {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        System.out.print("Enter a number: ");
        try {
            int number = scanner.nextInt();
            System.out.println("The number is: " + number);
        } catch (InputMismatchException e) {
            System.err.println("Invalid input");
        }
    }
}
```

  </TabItem>
  <TabItem value="cpp" label="C++">

```cpp
#include <iostream>
#include <stdexcept>

int main() {
    std::cout << "Enter a number: ";
    try {
        int number;
        std::cin >> number;
        if (std::cin.fail()) {
            throw std::invalid_argument("Invalid input");
        }
        std::cout << "The number is: " << number << std::endl;
    } catch (const std::invalid_argument& e) {
        std::cerr << e.what() << std::endl;
    }
    return 0;
}
```

  </TabItem>
  <TabItem value="python" label="Python">

```python
import sys

try:
    input_str = input("Enter a number: ")
    number = int(input_str)
    print("The number is:", number)
except ValueError:
    print("Invalid input")
```

  </TabItem>
</Tabs>

In this example, we try to catch the error when the input is not an integer.

## Types of Exception

### Checked Exceptions

### Unchecked Exceptions

### Error

## Throwing Exceptions

Throwing an exception is a way of signaling that an error or exceptional
condition has occurred during the execution of a program. This can help improve
the reliability of the program by allowing the program to gracefully handle
errors and prevent them from causing the program to crash or produce incorrect
results.

To throw an exception, you first need to create an instance of the
exception class that corresponds to the type of error you want to throw. For
example, to signal that a file could not be found, you would create an instance
of the `FileNotFoundException` class. You can then throw this exception using
the throw keyword followed by the exception object. Here's an example:

```java
public void readFile(String filename) throws FileNotFoundException {
    File file = new File(filename);
    if (!file.exists()) {
        throw new FileNotFoundException("File not found: " + filename);
    }
    // code to read file...
}
```

In this example, if the file does not exist, an instance of
`FileNotFoundException` is created with a message indicating the name of the
file that could not be found. This exception is then thrown using the throw
keyword. The throws keyword in the method signature indicates that the method
may throw this exception and that calling code must handle it accordingly.

When an exception is thrown, it interrupts the normal flow of execution and is
passed up the call stack until it is caught by an appropriate catch block or
until it reaches the top level of the program, at which point it will terminate
the program.

